spring.application.name=demorpg
spring,applicacion.name=SpringBootSecurityPostgresqlApplication
spring.datasource.url=jdbc:postgresql://victordb-pg-victor.g.aivencloud.com:12757/defaultdb?useSSL=false
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_gcxcyt0Hujo8sIwtNJW
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
